# Generated by Django 2.0.6 on 2018-07-13 12:32

from django.db import migrations, models
import django.utils.timezone

from pokepare.utils import OverwriteStorage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The set name.', max_length=500)),
                ('code', models.CharField(help_text='The code name of the set.', max_length=50)),
                ('series', models.CharField(blank=True, help_text='The series the set belongs to.', max_length=50, null=True)),
                ('realase_date', models.CharField(blank=True, help_text='The date the set was released.', max_length=20, null=True)),
                ('total_cards', models.PositiveIntegerField(blank=True, null=True)),
                ('symbol_url', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('symbol', models.ImageField(blank=True, null=True, storage=OverwriteStorage(), upload_to='sets/symbols/')),
                ('logo', models.ImageField(blank=True, null=True, storage=OverwriteStorage(), upload_to='sets/logos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
