# Generated by Django 2.0.6 on 2020-04-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardsets', '0003_auto_20180713_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='CardSet',
        ),
    ]
