# Generated by Django 2.0.6 on 2020-04-06 16:46

from django.db import migrations, models
from pokepare.utils import OverwriteStorage


class Migration(migrations.Migration):

    dependencies = [
        ('cardsets', '0004_auto_20200406_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=OverwriteStorage(), upload_to='cardsets/logos/'),
        ),
    ]
