FROM python:3

# Update with new repo
RUN apt-get update

# Install software 
RUN apt-get install -y git

COPY requirements.txt ./requirements.txt
RUN pip install numpy
RUN pip install -r /requirements.txt

WORKDIR /usr/src/app

EXPOSE 8060

# different settings from local dev
ENV DJANGO_SETTINGS_MODULE=pokepare.settings.staging

CMD [ "gunicorn", "pokepare.wsgi", "-b", "0.0.0.0:8060" ]