FROM python:3.6.10-stretch

# Update with new repo
RUN apt-get update

# Install software
RUN apt-get install -y git libfreetype6-dev

COPY requirements.txt ./requirements.txt
RUN pip install numpy Cython
RUN pip install -r /requirements.txt

WORKDIR /usr/src/app

EXPOSE 8060

# different settings from local dev
ENV DJANGO_SETTINGS_MODULE=pokepare.settings.production

CMD [ "gunicorn", "pokepare.wsgi", "-b", "0.0.0.0:8060" ]