# Generated by Django 2.0.6 on 2018-07-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('front_image', models.URLField(blank=True, null=True)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
    ]
