# Generated by Django 2.0.6 on 2018-07-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0006_auto_20180715_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='name_jp',
        ),
    ]
