# Generated by Django 3.0.5 on 2020-05-10 19:38

from django.db import migrations, models
import django.db.models.deletion
import pokepare.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0007_auto_20180715_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='name',
        ),
        migrations.CreateModel(
            name='PokemonTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, storage=pokepare.utils.OverwriteStorage(), upload_to='pokemons/')),
                ('pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_translations', to='pokemons.Pokemon')),
            ],
        ),
    ]
