# Generated by Django 3.0.5 on 2020-05-12 20:04

from django.db import migrations, models
import pokepare.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0008_auto_20200510_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemontranslations',
            name='image',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='front_sprite',
            field=models.ImageField(blank=True, null=True, storage=pokepare.utils.OverwriteStorage(), upload_to='pokemons/'),
        ),
    ]
