# Generated by Django 2.0.6 on 2018-06-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('card_set', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=5)),
                ('url', models.URLField()),
            ],
        ),
    ]
