# Generated by Django 2.0.6 on 2018-07-05 11:41

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from pokepare.utils import OverwriteStorage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        help_text='The card name.', max_length=500
                    )
                ),
                (
                    'card_set',
                    models.CharField(
                        blank=True,
                        help_text='The set the card appears in (ex. BREAKthrough, Phantom Forces, Jungle, etc.)',  # noqa
                        max_length=100, null=True
                    )
                ),
                (
                    'image_hash',
                    models.PositiveIntegerField(blank=True, null=True)
                ),
                (
                    'series',
                    models.CharField(
                        blank=True,
                        help_text='The series the card appears in (ex. Base, XY, EX, etc.)',  # noqa
                        max_length=50, null=True
                    )
                ),
                (
                    'language',
                    models.CharField(
                        blank=True, help_text='The language of the card.',
                        max_length=5, null=True
                    )
                ),
                (
                    'url',
                    models.URLField(blank=True, null=True)
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True, null=True,
                        storage=OverwriteStorage(), upload_to='cards/'
                    )
                ),
                (
                    'condition',
                    models.CharField(
                        blank=True, max_length=50, null=True
                    )
                ),
                (
                    'edition',
                    models.CharField(
                        blank=True, max_length=50, null=True
                    )
                ),
                (
                    'rarity',
                    models.CharField(
                        blank=True,
                        help_text='Common/Holo/Shining/Full Art...',
                        max_length=50, null=True
                    )
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    )
                ),
                (
                    'pokemon',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cards', to='pokemons.Pokemon'
                    )
                ),
                (
                    'number_in_set',
                    models.CharField(
                        blank=True,
                        help_text='The number of the card for the set it was released in. Found on the bottom right side of the card.',  # noqa
                        max_length=20, null=True
                    )
                ),
                (
                    'artist',
                    models.CharField(
                        blank=True, help_text='The artist of the card.',
                        max_length=200, null=True
                    )
                ),
                (
                    'card_set_code',
                    models.CharField(
                        blank=True, help_text='The unique code of the set (ex. base1, xy5, ex3)',  # noqa
                        max_length=20, null=True)
                ),
                (
                    'hp',
                    models.CharField(
                        blank=True,
                        help_text='The number of the card for the set it was released in. Found on the bottom right side of the card.',  # noqa
                        max_length=10,
                        null=True
                    )
                ),
                (
                    'national_pokedex_number',
                    models.IntegerField(
                        blank=True,
                        help_text='The national pokedex number for a card that features a Pokémon supertype.',  # noqa
                        null=True
                    )
                ),
                (
                    'supertype',
                    models.CharField(
                        blank=True,
                        help_text='Pokémon/Trainer/Energy',
                        max_length=100, null=True
                    )
                ),
                (
                    'types',
                    models.CharField(
                        blank=True,
                        help_text='The types of the card. These typically appear in the top right of card, and are denoted by energy symbol (ex. Fire, Fighting, Psychic, etc.)',  # noqa
                        max_length=100, null=True
                    )
                ),
                (
                    'image_url',
                    models.URLField(
                        default='/static/assets/pokepare_card.png',
                        help_text='The front image of the card.'
                    )
                ),
                (
                    'unique_id',
                    models.CharField(
                        blank=True,
                        help_text='A unique id for this card. It is made up by taking the set code and concatenating the card number to it. (ex. xy1-1)',  # noqa
                        max_length=100, null=True
                    )
                ),
                (
                    'prices',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        default=list,
                        null=True
                    )
                ),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
