# Generated by Django 2.0.6 on 2018-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='version',
        ),
        migrations.RemoveField(
            model_name='card',
            name='year',
        ),
        migrations.AddField(
            model_name='card',
            name='artist',
            field=models.CharField(blank=True, help_text='The artist of the card.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_set_code',
            field=models.CharField(blank=True, help_text='The unique code of the set (ex. base1, xy5, ex3)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='hp',
            field=models.PositiveIntegerField(blank=True, help_text='The number of the card for the set it was released in. Found on the bottom right side of the card.', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='nationalPokedexNumber',
            field=models.PositiveIntegerField(blank=True, help_text='The national pokedex number for a card that features a Pokémon supertype.', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='subtype',
            field=models.CharField(blank=True, help_text='MEGA/BREAK/Supporter...', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='supertype',
            field=models.CharField(blank=True, help_text='Pokémon/Trainer/Energy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='types',
            field=models.CharField(blank=True, help_text='The types of the card. These typically appear in the top right of card, and are denoted by energy symbol (ex. Fire, Fighting, Psychic, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_set',
            field=models.CharField(blank=True, help_text='The set the card appears in (ex. BREAKthrough, Phantom Forces, Jungle, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.URLField(default='/static/img/pokepare_card.png', help_text='The front image of the card.'),
        ),
        migrations.AlterField(
            model_name='card',
            name='language',
            field=models.CharField(blank=True, help_text='The language of the card.', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(help_text='The card name.', max_length=500),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='The number of the card for the set it was released in. Found on the bottom right side of the card.', null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, help_text='Common/Holo/Shining/Full Art...', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.CharField(blank=True, help_text='The series the card appears in (ex. Base, XY, EX, etc.)', max_length=50, null=True),
        ),
    ]
