# Generated by Django 2.0.6 on 2018-06-14 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20180614_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
