# Generated by Django 2.0.6 on 2018-07-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20180614_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.URLField(default='C:\\Users\\PC\\Desktop\\projets_OC\\pokepare_project\\staticfiles/img/pokepare_card.png'),
        ),
    ]
