# Generated by Django 2.0.6 on 2018-07-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.URLField(default='/static//img/pokepare_card.png'),
        ),
    ]
