# Generated by Django 2.0.6 on 2018-07-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20180703_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('front_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.URLField(default='/static/img/pokepare_card.png'),
        ),
    ]
