# Generated by Django 2.0.6 on 2018-07-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20180705_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number_in_set',
            field=models.CharField(blank=True, help_text='The number of the card for the set it was released in. Found on the bottom right side of the card.', max_length=20, null=True),
        ),
    ]
