# Generated by Django 2.0.6 on 2018-07-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20180703_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
