# Generated by Django 2.0.6 on 2018-07-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20180705_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_hash',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
