# Generated by Django 2.0.6 on 2018-07-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_remove_pokemon_cards'),
        ('cards', '0007_delete_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemons.Pokemon'),
        ),
    ]
