# Generated by Django 2.0.6 on 2018-07-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_card_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='hp',
            field=models.IntegerField(blank=True, help_text='The number of the card for the set it was released in. Found on the bottom right side of the card.', null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='nationalPokedexNumber',
            field=models.IntegerField(blank=True, help_text='The national pokedex number for a card that features a Pokémon supertype.', null=True),
        ),
    ]
