# Generated by Django 2.0.6 on 2018-07-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pokemons.Pokemon'),
        ),
    ]
