# Generated by Django 2.0.6 on 2018-07-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20180709_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.AddField(
            model_name='card',
            name='image_url',
            field=models.URLField(default='/static/img/pokepare_card.png', help_text='The front image of the card.'),
        ),
    ]
