# Generated by Django 2.0.6 on 2018-07-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20180709_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='nationalPokedexNumber',
        ),
        migrations.AddField(
            model_name='card',
            name='national_pokedex_number',
            field=models.IntegerField(blank=True, help_text='The national pokedex number for a card that features a Pokémon supertype.', null=True),
        ),
    ]
