# Generated by Django 2.0.6 on 2018-07-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20180709_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='unique_id',
            field=models.CharField(blank=True, help_text='A unique id for this card. It is made up by taking the set code and concatenating the card number to it. (ex. xy1-1)', max_length=100, null=True),
        ),
    ]
