# Generated by Django 2.0.6 on 2018-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_card_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/cards/'),
        ),
    ]
