# Generated by Django 2.0.6 on 2018-07-17 16:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_auto_20180713_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='prices',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
