# Generated by Django 2.0.6 on 2018-07-21 12:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_auto_20180717_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='prices',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
