# Generated by Django 3.1.6 on 2021-07-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_auto_20180721_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The subtype name.', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.URLField(default='/static/assets/pokepare_card.png', help_text='The front image of the card.'),
        ),
        migrations.RemoveField(
            model_name='card',
            name='subtype',
        ),
        migrations.AddField(
            model_name='card',
            name='subtype',
            field=models.ManyToManyField(to='cards.SubType'),
        ),
    ]
