# Generated by Django 3.0.5 on 2020-05-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_auto_20180721_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.URLField(default='/static/assets/pokepare_card.png', help_text='The front image of the card.'),
        ),
    ]
