# Generated by Django 2.0.6 on 2018-07-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='realase_date',
        ),
        migrations.AddField(
            model_name='set',
            name='release_date',
            field=models.CharField(blank=True, help_text='The date the set was released.', max_length=20, null=True),
        ),
    ]
