# Generated by Django 2.0.6 on 2018-07-13 12:43

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_auto_20180713_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='set',
            name='symbol',
        ),
        migrations.AddField(
            model_name='set',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.OverwriteStorage(), upload_to='sets/logos/'),
        ),
    ]
