# Generated by Django 3.1.6 on 2021-07-12 12:54

import django.db.models.deletion
from django.db import migrations, models

import pokepare.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True, max_length=100
                    )
                ),
                (
                    'iso639',
                    models.CharField(
                        max_length=10
                    )
                ),
                (
                    'iso3166',
                    models.CharField(
                        max_length=2
                    )
                ),
                (
                    'official',
                    models.BooleanField(
                        default=False
                    )
                ),
                (
                    'sprite',
                    models.CharField(
                        max_length=256
                    )
                ),
                (
                    'local_name',
                    models.CharField(
                        max_length=64
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True, max_length=100
                    )
                ),
                (
                    'evolves_from_species',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='pokemons.pokemonspecies'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonSpeciesName',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True, max_length=100
                    )
                ),
                (
                    'language',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pokemonspeciesname_language',
                        to='pokemons.language'
                    )
                ),
                (
                    'pokemon_species',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pokemonspeciesname',
                        to='pokemons.pokemonspecies'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'number',
                    models.PositiveIntegerField
                    (
                    )
                ),
                (
                    'front_sprite',
                    models.ImageField(
                        blank=True, null=True,
                        storage=pokepare.utils.OverwriteStorage(),
                        upload_to='pokemons/'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True, max_length=100
                    )
                ),
                (
                    'pokemon_species',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pokemon', to='pokemons.pokemonspecies'
                    )
                ),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True, max_length=100
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
