# Generated by Django 2.0.6 on 2018-07-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_remove_pokemon_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='front_image',
        ),
    ]
