# Generated by Django 2.0.6 on 2018-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_auto_20180710_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='front_image',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pokemons/'),
        ),
    ]
