# Generated by Django 2.0.6 on 2018-07-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0005_auto_20180713_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name_jp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
