# Generated by Django 3.0.5 on 2020-05-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0009_auto_20200512_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokemonTranslations',
            new_name='PokemonTranslation',
        ),
    ]
