# Generated by Django 3.0.5 on 2020-05-14 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0010_auto_20200512_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemontranslation',
            name='id',
        ),
        migrations.AddField(
            model_name='pokemontranslation',
            name='pokemon_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pokemons.Pokemon'),
            preserve_default=False,
        ),
    ]
