# Generated by Django 3.0.5 on 2020-05-16 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0011_auto_20200516_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pokemons.PokemonSpecies'),
        ),
    ]
