# Generated by Django 3.0.5 on 2020-05-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0015_auto_20200527_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='sprite',
            field=models.URLField(max_length=256),
        ),
    ]
