# Generated by Django 3.0.5 on 2020-06-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0016_auto_20200527_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonspecies',
            name='evolves_from_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemons.PokemonSpecies'),
        ),
    ]
