# Generated by Django 3.0.5 on 2020-06-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0017_pokemonspecies_evolves_from_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='local_name',
            field=models.CharField(default='en', max_length=64),
            preserve_default=False,
        ),
    ]
