# Generated by Django 3.0.5 on 2020-06-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0018_language_local_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='sprite',
            field=models.CharField(max_length=256),
        ),
    ]
